insert into Address (id, city, zipcode, country, state, street) values (1, 'Philadelphia', '19131', 'United States', 'Pennsylvania', '29290 Sutteridge Road');
insert into Address (id, city, zipcode, country, state, street) values (2, 'Charlotte', '28205', 'United States', 'North Carolina', '2 Heffernan Point');
insert into Address (id, city, zipcode, country, state, street) values (3, 'Virginia Beach', '23464', 'United States', 'Virginia', '60 Merry Drive');
insert into Address (id, city, zipcode, country, state, street) values (4, 'Akron', '44305', 'United States', 'Ohio', '703 Sunfield Lane');
insert into Address (id, city, zipcode, country, state, street) values (5, 'Saint Paul', '55188', 'United States', 'Minnesota', '863 Bultman Crossing');
insert into Address (id, city, zipcode, country, state, street) values (6, 'Houston', '77085', 'United States', 'Texas', '56996 Lawn Crossing');
insert into Address (id, city, zipcode, country, state, street) values (7, 'Las Vegas', '89130', 'United States', 'Nevada', '1 Moland Circle');
insert into Address (id, city, zipcode, country, state, street) values (8, 'Fort Smith', '72916', 'United States', 'Arkansas', '73106 Mesta Road');
insert into Address (id, city, zipcode, country, state, street) values (9, 'Homestead', '33034', 'United States', 'Florida', '52 Boyd Pass');
insert into Address (id, city, zipcode, country, state, street) values (10, 'Rochester', '55905', 'United States', 'Minnesota', '0 Shoshone Plaza');
insert into Address (id, city, zipcode, country, state, street) values (11, 'Saint Cloud', '56398', 'United States', 'Minnesota', '814 Grover Junction');
insert into Address (id, city, zipcode, country, state, street) values (12, 'Sandy', '84093', 'United States', 'Utah', '82371 Evergreen Lane');
insert into Address (id, city, zipcode, country, state, street) values (13, 'Atlanta', '31196', 'United States', 'Georgia', '4058 Dayton Parkway');
insert into Address (id, city, zipcode, country, state, street) values (14, 'Chesapeake', '23324', 'United States', 'Virginia', '23 Roth Alley');
insert into Address (id, city, zipcode, country, state, street) values (15, 'Huntington', '25711', 'United States', 'West Virginia', '0 Hermina Drive');
insert into Address (id, city, zipcode, country, state, street) values (16, 'Minneapolis', '55448', 'United States', 'Minnesota', '596 Dixon Point');
insert into Address (id, city, zipcode, country, state, street) values (17, 'Minneapolis', '55407', 'United States', 'Minnesota', '03105 Wayridge Place');
insert into Address (id, city, zipcode, country, state, street) values (18, 'Sacramento', '94257', 'United States', 'California', '6 Darwin Avenue');
insert into Address (id, city, zipcode, country, state, street) values (19, 'El Paso', '88584', 'United States', 'Texas', '07 Mandrake Way');
insert into Address (id, city, zipcode, country, state, street) values (20, 'Dallas', '75358', 'United States', 'Texas', '45 Ilene Center');
